### ISSUE TITLE
Need help in environment variable values

### ISSUE THREAD

**Issue by nitin-vavdiya** [FIWARE/keycloak-vc-issuer#19]
Hey there, 

I created docker images with the below Dockerfile

```
FROM quay.io/keycloak/keycloak:20.0.3
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
#ENV KC_SPI_THEME_ADMIN_DEFAULT=siop-2
ENV VCISSUER_WALTID_ADDRESS=https://core.ssikit.walt.id
ENV VCISSUER_WALTID_SIGNATORY_PORT=443
ENV VCISSUER_ISSUER_DID=did:web:tata.proofsense.in
ADD target/vc-issuer-SNAPSHOT-2.jar /opt/keycloak/providers/vc-issuer-SNAPSHOT-2.jar
```

I plan to use [General available APIs of wallt-id](https://docs.walt.id/v/ssikit/getting-started/rest-apis) .

![image](https://user-images.githubusercontent.com/45592624/235458674-2ce486c8-1d16-431e-b363-f6ee7eebd4a1.png)

While running the docker image, getting the below connection timeout:

```
2023-05-01 13:28:07,612 ERROR [org.fiware.keycloak.VCIssuerRealmResourceProviderFactory] (main) Was not able to initialize the issuer did. Issuing VCs is not available.: org.fiware.keycloak.WaltIdConnectException: Was not able to request did list from  walt-id.
	at org.fiware.keycloak.WaltIdClient.getDids(WaltIdClient.java:98)
	at org.fiware.keycloak.VCIssuerRealmResourceProviderFactory.existsDid(VCIssuerRealmResourceProviderFactory.java:153)
	at org.fiware.keycloak.VCIssuerRealmResourceProviderFactory.initializeIssuerDid(VCIssuerRealmResourceProviderFactory.java:109)
	at org.fiware.keycloak.VCIssuerRealmResourceProviderFactory.init(VCIssuerRealmResourceProviderFactory.java:79)
	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.<init>(QuarkusKeycloakSessionFactory.java:82)
	at org.keycloak.quarkus.runtime.KeycloakRecorder.configSessionFactory(KeycloakRecorder.java:80)
	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory957950182.deploy_4(Unknown Source)
	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory957950182.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.net.ConnectException: Connection timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at org.fiware.keycloak.WaltIdClient.getDids(WaltIdClient.java:92)
	... 32 more
Caused by: java.net.ConnectException: Connection timed out
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)


```

Can you please help with the ENV values in case we use Walt-id hosted APIs

**Comment by wistefan** [comment]
Hi, you cannot use the the generally available APIs, since that requires you to provide your private key to a 3rd party, which is highly unsecure.

**Comment by wistefan** [comment]
Then you should put whatever address your Walt is available at. And the ports for core and signatory api.

**Comment by nitin-vavdiya** [comment]
Assuming that core and signatory API should be available on the same host of wallet, right?

**Comment by wistefan** [comment]
yes

**Comment by nitin-vavdiya** [comment]
Thanks for the prompt response, 
Now, I am not getting connection errors with the below Dockerfile.
```
FROM quay.io/keycloak/keycloak:20.0.3
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
#ENV KC_SPI_THEME_ADMIN_DEFAULT=siop-2
ENV VCISSUER_WALTID_ADDRESS=https://wallet.walt.id
ENV VCISSUER_WALTID_SIGNATORY_PORT=443
ENV VCISSUER_WALTID_CORE_PORT=443
ENV VCISSUER_ISSUER_DID=did:did:key:z6MkhXRZPQ2JvehLPK7NhZ3PF3984bgbswXRuqGb7vB8Vt1H
ADD target/vc-issuer-SNAPSHOT-2.jar /opt/keycloak/providers/vc-issuer-SNAPSHOT-2.jar
```

Once I open the Issue VCs screen from the account console, there is no value in the drop-down:

![image](https://user-images.githubusercontent.com/45592624/235633456-52f9c547-2b70-4ccf-85f4-1f095928b619.png)

Based on the below logs, I suspect that issuer did is not correct:

```
2023-05-02 09:35:05,521 INFO  [org.fiware.keycloak.VCIssuerRealmResourceProviderFactory] (main) The configured did does not yet exist, we try to import did:did:key:z6MkhXRZPQ2JvehLPK7NhZ3PF3984bgbswXRuqGb7vB8Vt1H with the key.
```

I get this issue did from [issuer portal](https://issuer.walt.id/). 

My credential issed by issuer portal is:

```
{
    "type":
    [
        "VerifiableCredential",
        "VerifiableAttestation",
        "ProofOfResidence"
    ],
    "@context":
    [
        "https://www.w3.org/2018/credentials/v1"
    ],
    "id": "urn:uuid:b213705e-e79a-454b-a61e-284e24970aac",
    "issuer": "did:key:z6MkhXRZPQ2JvehLPK7NhZ3PF3984bgbswXRuqGb7vB8Vt1H",
    "issuanceDate": "2023-04-24T12:43:10Z",
    "issued": "2023-04-24T12:43:10Z",
    "validFrom": "2023-04-24T12:43:10Z",
    "expirationDate": "2022-06-22T14:11:44Z",
    "credentialSchema":
    {
        "id": "https://raw.githubusercontent.com/walt-id/waltid-ssikit-vclib/master/src/test/resources/schemas/ProofOfResidence.json",
        "type": "JsonSchemaValidator2018"
    },
    "credentialSubject":
    {
        "id": "did:key:z6MkkvBd7CkcMPnuwgexPbXLGboxLmx2pCurKwXfKREe2UiD",
        "address":
        {
            "countryName": "LU",
            "locality": "Steinfort",
            "postalCode": "L-8410",
            "streetAddress": "16 Route D' Arlon"
        },
        "dateOfBirth": "1993-04-08",
        "familyName": "Beron",
        "familyStatus": "Single",
        "firstNames": "Domink",
        "gender": "Male",
        "identificationNumber": "123456789",
        "nationality": "AT"
    },
    "credentialStatus":
    {
        "id": "https://essif.europa.eu/status/identity#verifiableID#1dee355d-0432-4910-ac9c-70d89e8d674e",
        "type": "CredentialStatusList2020"
    },
    "evidence":
    [
        {
            "documentPresence": "Physical",
            "evidenceDocument": "Passport",
            "id": "https://essif.europa.eu/tsr-va/evidence/f2aeec97-fc0d-42bf-8ca7-0548192d5678",
            "subjectPresence": "Physical",
            "type":
            [
                "DocumentVerification"
            ],
            "verifier": "did:ebsi:2962fb784df61baa267c8132497539f8c674b37c1244a7a"
        }
    ],
    "title": "Proof of Residence"
}
```

Can you please guide me here, what could be wrong here?

**Comment by wistefan** [comment]
It looks as if you did not configure any siop client. How does your client config look like?

**Comment by nitin-vavdiya** [comment]
Hey 
Are you referring to [this client](https://docs.walt.id/v/idpkit/configuration-and-setup/oidc-manager-configuration/client-registration#register-new-client)

If yes, what should be the redirect URL?

**Comment by nitin-vavdiya** [comment]
Can not create client using API:

```
curl 'http://localhost:8083/admin/realms/master/clients' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Authorization: bearer token' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "protocol": "SIOP-2",
    "clientId": "did:key:z6MkhXRZPQ2JvehLPK7NhZ3PF3984bgbswXRuqGb7vB8Vt1H",
    "name": "SIOP",
    "description": "",
    "publicClient": false,
      "surrogateAuthRequired": false,
    "authorizationServicesEnabled": false,
    "serviceAccountsEnabled": false,
    "implicitFlowEnabled": false,
      "bearerOnly": false,
        "consentRequired": false,
    "directAccessGrantsEnabled": false,
    "standardFlowEnabled": true,  
    "frontchannelLogout": false,
    "alwaysDisplayInConsole": false,
    "enabled": true,
    "supportedVCTypes":
    [
        {
            "type": "PacketDeliveryService",
            "format": "ldp_vc"
        },
        {
            "type": "PacketDeliveryService",
            "format": "jwt_vc_json"
        }
    ]
}'
```

Error:

```
{"error":"Unrecognized field \"supportedVCTypes\" (class org.keycloak.representations.idm.ClientRepresentation), not marked as ignorable (43 known properties: \"enabled\", \"clientAuthenticatorType\", \"redirectUris\", \"clientId\", \"authenticationFlowBindingOverrides\", \"authorizationServicesEnabled\", \"name\", \"implicitFlowEnabled\", \"registeredNodes\", \"nodeReRegistrationTimeout\", \"publicClient\", \"attributes\", \"protocol\", \"webOrigins\", \"protocolMappers\", \"id\", \"baseUrl\", \"surrogateAuthRequired\", \"adminUrl\", \"fullScopeAllowed\", \"frontchannelLogout\", \"clientTemplate\", \"origin\", \"defaultClientScopes\", \"directGrantsOnly\", \"rootUrl\", \"secret\", \"useTemplateMappers\", \"notBefore\", \"useTemplateScope\", \"standardFlowEnabled\", \"description\", \"directAccessGrantsEnabled\", \"alwaysDisplayInConsole\", \"useTemplateConfig\", \"serviceAccountsEnabled\", \"optionalClientScopes\", \"consentRequired\", \"access\", \"bearerOnly\", \"registrationAccessToken\", \"defaultRoles\", \"authorizationSettings\"])\n at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 19, column: 6] (through reference chain: org.keycloak.representations.idm.ClientRepresentation[\"supportedVCTypes\"])"ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
```

**Comment by wistefan** [comment]
If you are using the keycloak clients api for that, you need to use the matching format;) Check the 2nd example from the protocol doc: https://github.com/wistefan/keycloak-vc-issuer#protocol
